# Generated by Django 3.0.7 on 2020-09-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Y', 'Yet To Start'), ('P', 'In Progress'), ('I', 'In Review'), ('C', 'Completed')], max_length=100)),
                ('Priority', models.CharField(choices=[('L', 'Low'), ('I', 'Intermediate'), ('H', 'High')], max_length=100)),
                ('assignees', models.CharField(max_length=250)),
            ],
        ),
    ]
