# Generated by Django 3.0.7 on 2020-09-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Priority',
            new_name='priority',
        ),
    ]
