# Generated by Django 3.0.7 on 2020-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTodo', '0003_auto_20200929_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.CharField(max_length=20),
        ),
    ]
